default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: poc_development

test:
  <<: *default
  database: poc_test

production:
  <<: *default
  database: poc_production
  username: poc
  password: <%= ENV['POC_DATABASE_PASSWORD'] %>
